CREATE OR REPLACE VIEW getCustomer_info04 AS
SELECT A.CUSTOMER_ID, A.NAME, B.COUNTRY_NAME, A.BUDGET, A.USED, COUNT(C.AUDIT_ID) AS ITEM_AUDIT
FROM customer A
LEFT OUTER JOIN country B ON A.COUNTRY_CODE = B.COUNTRY_CODE 
LEFT OUTER JOIN `audit` C ON A.CUSTOMER_ID = C.CUSTOMER_ID
WHERE A.COUNTRY_CODE = "US" AND A.USED <= 300000 GROUP BY A.CUSTOMER_ID ORDER BY
A.USED DESC;


SELECT * FROM `getCustomer_info04`;