# mst_customer
CREATE OR REPLACE VIEW mst_customer AS
SELECT CUSTOMER_ID AS CM_ID, NAME AS CM_NAME, EMAIL AS CM_EMAIL, COUNTRY_CODE AS CM_COUNTRY_CODE, BUDGET AS CM_BUDGET, USED AS CM_USED
FROM customer;

# mst_country
CREATE OR REPLACE VIEW mst_country AS
SELECT COUNTRY_CODE AS CT_COUNTRY_CODE, COUNTRY_NAME AS CT_COUNTRY_NAME
FROM country;

# trn_audit
CREATE OR REPLACE VIEW trn_audit AS
SELECT AUDIT_ID AS CM_AUDIT_ID, CUSTOMER_ID AS CM_ID, LOG_DATE AS CM_LOG_DATE, USED AS CM_USED
FROM audit;

# trn_report
CREATE OR REPLACE VIEW trn_report AS
SELECT A.CM_ID, A.CM_NAME, B.CT_COUNTRY_NAME, A.CM_BUDGET, A.CM_USED, COUNT(C.CM_AUDIT_ID) AS ITEM_AUDIT
FROM mst_customer A
LEFT OUTER JOIN mst_country B ON A.CM_COUNTRY_CODE = B.CT_COUNTRY_CODE 
LEFT OUTER JOIN trn_audit C ON A.CM_ID = C.CM_ID
WHERE A.CM_USED <= 300000 AND B.CT_COUNTRY_CODE = 'US'
GROUP BY A.CM_ID
ORDER BY A.CM_ID DESC;


SELECT * FROM `trn_report`;